repos:
  - repo: https://github.com/alessandrojcm/commitlint-pre-commit-hook
    rev: v7.0.1
    hooks:
        - id: commitlint
          stages: [commit-msg]
          additional_dependencies: ["@commitlint/config-conventional"]
